[package]
name = "bsutils"
version = "1.0.0"
edition = "2021"
authors = [ "Nathan ROYER <nathan.royer.pro@gmail.com>" ]
description = "Low Memory Footprint Utilities (String, HashMap, JSON)"
license = "MIT"
categories = [ "data-structures", "parser-implementations", "no-std" ]
keywords = [ "memory", "hashmap", "arc", "json", "no_std" ]
repository = "https://github.com/NathanRoyer/bsutils"

[lib]
path = "lib.rs"

[dependencies]
litemap = { version = "0.7.0", optional = true }
ahash   = { version = "0.8.3", optional = true, default-features = false, features = [ "compile-time-rng" ] }

[features]
default = [ "hashmap", "litemap", "json", "rostring" ]
rostring = []
json = [ "dep:litemap", "dep:ahash", "rostring" ]
hashmap = [ "dep:ahash", "dep:litemap" ]
litemap = [ "dep:litemap" ]

[build-dependencies]
rand = "0.8.5"
